MVCForms/MVCForms/Models/FormsModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace MVCForms.Models
{
    public class FormsModel
    {
        public int Id { get; set; }

        [Required(ErrorMessage = "Please Enter Name")]
        public string Name { get; set; }

        [Required(ErrorMessage = "Please Enter Email Id")]
        public string Email { get; set; }

        public Genders Gender { get; set; }
        public DateTime DOB { get; set; }

        [Required(ErrorMessage = "Password is Required")]
        public string Pswd { get; set; }

        public string RetyPswd { get; set; }

        [Required(ErrorMessage = "Enter Home Address")]
        public string Home_Address { get; set; }

        [Required(ErrorMessage = "Enter Office Address")]
        public string Office_Address { get; set; }

        [Required(ErrorMessage = "Enter Mobile Number")]
        public decimal Mobile_Number { get; set; }

        [Required(ErrorMessage = "Enter Phone Number")]
        public decimal Phone_Number { get; set; }


        public string State { get; set; }
        public string City { get; set; }
        public enum Genders
        {
            Male,
            Female
        }
    }
}

MVCForms/MVCForms/Controllers/FormController.cs
using MVCForms.Models;
using MVCForms.Repository;
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Data;
using System.Data.SqlClient;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace MVCForms.Controllers
{
    public class FormController : Controller
    {
        //get: all data
        public ActionResult GetAllFormData(int id)
        {
            FormRepository repo = new FormRepository();
            ModelState.Clear();
            return View(repo.GetAllData().Where(x=>x.Id==id));
        }

        public ActionResult Select(int? Id)
        {
            FormRepository repo = new FormRepository();
            ModelState.Clear();
            var result = repo.GetAllData();
            return View(result);
        }
       
        //insert
        public ActionResult Insert()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Insert(FormsModel model)
        {
            FormRepository repo = new FormRepository();
            if (repo.AddNew(model))
            {
                ViewBag.AddNewSuccessFull = "Details Added Successfully";
            }
            return View();
        }

        //Delete
        public ActionResult Delete(int Id)
        {
            FormRepository repo = new FormRepository();
            if (repo.DeleteData(Id))
                return RedirectToAction("Select");
            else
                return View();
        }

        //GET: update
        public ActionResult Update(int id)
        {
            FormRepository repo = new FormRepository();

            var result = repo.GetAllData().Find(x=>x.Id==id);
            return View(result);
        }

       //Post: Update
        [HttpPost]
        public ActionResult Update(int Id, FormsModel model)
        {
            FormRepository repo = new FormRepository();
            repo.UpdateData(model);
            return RedirectToAction("Select");
        }
    }
}

MVCForms/MVCForms/Views/Form/Delete.cshtml
@model MVCForms.Models.FormsModel

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>
@using (@Html.BeginForm("Delete", "Form", FormMethod.Post))
{
    <table>
        <tr>
            <td>
                @Html.Label("Delete", "Delete")
            </td>
            <td>@Html.TextBoxFor(x => x.Id)</td>
        </tr>
        <tr>
            <td>
                <input id="Submit1" type="submit" value="Delete" />
            </td>
            <td>@Html.ActionLink("Return to Display All data","Select")</td>
        </tr>
    </table>
}

MVCForms/MVCForms/Views/Form/GetAllFormData.cshtml
@{
    ViewBag.Title = "GetAllFormData";
}

<h2>GetAllFormData</h2>
@Html.ActionLink("Return to main","Select")
<table border="1">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th>Home_Address</th>
            <th>Office_Address</th>
            <th>Mobile_Number</th>
            <th>Phone_Number</th>
            <th>State</th>
            <th>City</th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@item.Home_Address</td>
                <td>@item.Office_Address</td>
                <td>@item.Mobile_Number</td>
                <td>@item.Phone_Number</td>
                <td>@item.State</td>
                <td>@item.City</td>
            </tr> 
        }
    </table>

MVCForms/MVCForms/Views/Form/Insert.cshtml
@{
    ViewBag.Title = "Insert";
}
@using MVCForms.Models
@model FormsModel

<h2>Insert</h2>
  <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />

@using (Html.BeginForm("Insert", "Form", FormMethod.Post))
{
    <table class="table table-striped">
        <tr>
            <td>
                @Html.Label("Name", "Name : ")
            </td>
            <td>
                @Html.TextBoxFor(x => x.Name)
            </td>
            <td>
                @Html.ValidationMessage("Name","")
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Email","Email : ")
            </td>
            <td>
                 @Html.TextBoxFor(x=>x.Email)
            </td>
            <td>
                @Html.ValidationMessage("Name","")
            </td>
        </tr>
        <tr>
             <td>
                @Html.Label("Gender","Gender : ")
            </td>
            <td>
                 @Html.DropDownListFor(x=>x.Gender,new SelectList(Enum.GetValues(typeof(MVCForms.Models.FormsModel.Genders))),"Select Gender")
            </td>
        </tr>
        @*<tr>
            <td>
                @Html.Label("DOB","Date of Birth : ")
            </td>
            <td>
               
            </td>
        </tr>*@
        
        <tr>
            <td>
                @Html.Label("Pswd","Password : ")
            </td>
            <td>
               @Html.PasswordFor(x=>x.Pswd)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("RetypePswd","Retypre-Password : ")
            </td>
            <td>
                @Html.PasswordFor(x=>x.RetyPswd)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Home_Address","Home Address : ")
            </td>
            <td>
               @Html.TextAreaFor(x=>x.Home_Address)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Office_Address","Office Address : ")
            </td>
            <td>
                @Html.TextAreaFor(x=>x.Office_Address)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Mobile_Number","Mobile Number : ")
            </td>
            <td>
                @Html.TextBoxFor(x=>x.Mobile_Number)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Phone_Number","Phone Number : ")
            </td>
            <td>
                @Html.TextBoxFor(x=>x.Phone_Number)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("State","State : ")
            </td>
            <td>
                @Html.TextBoxFor(x=>x.State)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("City","City : ")
            </td>
            <td>
                @Html.TextBoxFor(x=>x.City)
            </td>
        </tr>
        <tr>
            <td>
                <input type="submit" class="btn btn-default" value="Submit"/>
            </td>
        </tr>
    </table> 
}
<script type="text/javascript">
    
</script>

MVCForms/MVCForms/Views/Form/Select.cshtml
@model List<MVCForms.Models.FormsModel>
<html>
<head>
    <title>Select </title>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js"></script>
    <link href="~/Content/bootstrap-theme.css" rel="stylesheet" />
    <link href="~/Content/bootstrap-theme.min.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.css" rel="stylesheet" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" />
</head>
@{
    ViewBag.Title = "Select";
}

<h2>Select</h2>
    @Html.ActionLink("Add New", "Insert", "", new {@class="btn btn-default"})
<body>
    <table class="table table-striped" border="1">
        <tr>
            <th>Id</th>
            <th>Name</th>
            <th>Email</th>
            <th></th>
            <th>Action</th>
            <th></th>
        </tr>
        @foreach (var item in Model)
        {
            <tr>
                <td>@item.Id</td>
                <td>@item.Name</td>
                <td>@item.Email</td>
                <td>@Html.ActionLink("Update", "Update", new { id=item.Id})</td>
                <td>@Html.ActionLink("Details", "GetAllFormData", new { id=item.Id})</td>
                <td>@Html.ActionLink("Delete", "Delete", new { id=item.Id})</td>
            </tr> 
        }
    </table>
</body>
</html>

MVCForms/MVCForms/Views/Form/Update.cshtml
@model MVCForms.Models.FormsModel

@{
    ViewBag.Title = "Update";
}

<h2>Update</h2>
@using (@Html.BeginForm("Update", "Form", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    @Html.HiddenFor(x => x.Id)
   
    <table>
        
        <tr>
            <td>@Html.Label("Name", "Name : ")</td>
            <td>@Html.TextBoxFor(x => x.Name)</td>
        </tr>
        <tr>
            <td>@Html.Label("Email", "Email : ")</td>
            <td>@Html.TextBoxFor(x => x.Email)</td>
        </tr>
        <tr>
             <td>
                @Html.Label("Gender", "Gender : ")
            </td>
            <td>
                 @Html.DropDownListFor(x => x.Gender, new SelectList(Enum.GetValues(typeof(MVCForms.Models.FormsModel.Genders))), "Select Gender")
            </td>
        </tr>
        @*<tr>
            <td>
                @Html.Label("DOB","Date of Birth : ")
            </td>
            <td>
               
            </td>
        </tr>*@
        <tr>
            <td>
                @Html.Label("Pswd", "Password : ")
            </td>
            <td>
               @Html.TextBoxFor(x => x.Pswd)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("RetypePswd", "Retypre-Password : ")
            </td>
            <td>
                @Html.TextBoxFor(x => x.RetyPswd)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Home_Address", "Home Address : ")
            </td>
            <td>
               @Html.TextAreaFor(x => x.Home_Address)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Office_Address", "Office Address : ")
            </td>
            <td>
                @Html.TextAreaFor(x => x.Office_Address)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Mobile_Number", "Mobile Number : ")
            </td>
            <td>
                @Html.TextBoxFor(x => x.Mobile_Number)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("Phone_Number", "Phone Number : ")
            </td>
            <td>
                @Html.TextBoxFor(x => x.Phone_Number)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("State", "State : ")
            </td>
            <td>
                @Html.TextBoxFor(x => x.State)
            </td>
        </tr>
        <tr>
            <td>
                @Html.Label("City", "City : ")
            </td>
            <td>
                @Html.TextBoxFor(x => x.City)
            </td>
        </tr>
        <tr>
            <input id="Submit1" type="submit" value="update" />
        </tr>
    </table> 
}